/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_haidozo_sudoku_MainActivity */

#ifndef _Included_de_haidozo_sudoku_MainActivity
#define _Included_de_haidozo_sudoku_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef de_haidozo_sudoku_MainActivity_REQUEST_CODE
#define de_haidozo_sudoku_MainActivity_REQUEST_CODE 100L
/*
 * Class:     de_haidozo_sudoku_MainActivity
 * Method:    AnalyzePicture
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_haidozo_sudoku_MainActivity_AnalyzePicture
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
