/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_haidozo_schanner_MainActivity */

#ifndef _Included_de_haidozo_schanner_MainActivity
#define _Included_de_haidozo_schanner_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_haidozo_schanner_MainActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_haidozo_schanner_MainActivity_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
