/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_haidozo_sudoku_SudokuBoardRecognition */

#ifndef _Included_de_haidozo_sudoku_SudokuBoardRecognition
#define _Included_de_haidozo_sudoku_SudokuBoardRecognition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_haidozo_sudoku_SudokuBoardRecognition
 * Method:    extract
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_haidozo_sudoku_SudokuBoardRecognition_extract
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
